name: docker
on:
  pull_request: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v1
      - name: docker buildx build --load
        run: |
          docker buildx build \
            -t tailscale2cloudflare \
            --load \
            .
      - name: docker run smoke test
        run: docker run --rm tailscale2cloudflare --help